### ISSUE TITLE
How to do JSON formatting?

### ISSUE THREAD

**Issue by zaydek** [samber/slog-logrus#2]
Hi there, thanks for making this package. I usually use a pattern like this to turn on JSON formatting or human-readable logging:

```go
	_, production := os.LookupEnv("RAILWAY_ENVIRONMENT_NAME")
	if production {
		gin.SetMode(gin.ReleaseMode)
		logrus.SetFormatter(&logrus.JSONFormatter{CallerPrettyfier: pretty})
	} else {
		logrus.SetFormatter(&logrus.TextFormatter{CallerPrettyfier: pretty})
	}
```
	
I want to start using this package but I'm a little confused how to make use of JSON formatting. Do I tell logrus to use the JSON logger or does slog-logrus or slog need to be made aware? Thanks.

**Comment by samber** [comment]
just declare this: `logrus.SetFormatter(&logrus.JSONFormatter{CallerPrettyfier: pretty})`

When you call `slog.Error(...)`, the record will be forwarded into logrus.

Please note that in your example, you are updating the default logrus logger. So you have to instanciate slog-logrus with no logrus logger.

**Comment by zaydek** [comment]
Ah excellent thanks. Sorry I was just a little confused who receives what information. Here's a working reference based on your example for anyone to gleam.

```go
package main

import (
	"fmt"
	"log/slog"
	"time"

	sloglogrus "github.com/samber/slog-logrus/v2"
	"github.com/sirupsen/logrus"
)

func main() {
	logrusLogger := logrus.New()
	logrusLogger.SetFormatter(&logrus.JSONFormatter{})
	logrusLogger.SetLevel(logrus.WarnLevel)

	logger := slog.New(
		sloglogrus.Option{
			Logger: logrusLogger,
		}.NewLogrusHandler(),
	)
	logger = logger.
		With("environment", "dev").
		With("release", "v1.0.0")

	// log error
	logger.
		With("category", "sql").
		With("query.statement", "SELECT COUNT(*) FROM users;").
		With("query.duration", 1*time.Second).
		With("error", fmt.Errorf("could not count users")).
		Error("caramba!")

	// log user signup
	logger.
		With(
			slog.Group("user",
				slog.String("id", "user-123"),
				slog.Time("created_at", time.Now()),
			),
		).
		Info("user registration")
}
```

Feel free to close this if there's no more context to add @samber.

**Comment by samber** [comment]
looks good 👌
